### ISSUE TITLE
README.md 업데이트 

### ISSUE THREAD

**Issue by SeungrokYoon** [wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-1-7#29]
# Todo
- [ ] README.md 업데이트 
- [ ] 베스트 프랙티스 도출과정 노션에 정리
  - [ ] 베스트 프랙티스는 이거다! 
  - [ ] 베스트 프랙티스인 이유는?

**Comment by 5unk3n** [comment]
리드미에서 사용하기 위한 이미지를 이 코멘트에 정리하겠습니다.

![image](https://github.com/wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-1-7/assets/97281800/b4cfcfd3-b451-499e-beb4-c353b9a94046)
![2023-08-25_5 33 09](https://github.com/wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-1-7/assets/97281800/341ac780-1028-4db5-911d-1821a457292a)
![image (1)](https://github.com/wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-1-7/assets/97281800/689a4635-d63d-4534-9754-eec6d4e8b77f)

**Comment by SeungrokYoon** [comment]
![image](https://github.com/wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-1-7/assets/44149596/6d856380-9843-49d7-8f66-56050fec6ee8)

**Comment by SeungrokYoon** [comment]
![image](https://github.com/wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-1-7/assets/44149596/d7d75034-20d7-4879-9c70-51cbdcdce483)
